### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by LordNex** [PaulAnnekov/ukrainealarm#1]
Is this only for the Ukrainian area or can it be adapted for anywhere? I mean, if I live in San Diego and Russian forces targeted me, would I know?

**Comment by PaulAnnekov** [comment]
Yes, it's only for Ukrainian area.
This library uses an API developed by a company [Stfalcon](https://stfalcon.com) affiliated with Ukrainian government. I don't think US government will expose their data to Stfalcon. Even if they do, it will be another, global API.
