### ISSUE TITLE
Не приходит ключ

### ISSUE THREAD

**Issue by ntguest** [PaulAnnekov/ukrainealarm#2]
пробовал 2 разных номера и 2 почты - гуглевую и ukr.net
спам проверял
ключи не приходят

**Comment by PaulAnnekov** [comment]
Каждая заявка рассматривается индивидуально. Поэтому возможна задержка.
Мне кажется, что саппорт Ukraine Alarm неправильно поняли для чего я собираюсь использовать их API. Они ожидали, что их ключи будут просить разработчики производных приложений, которыми уже будут пользоваться конечные пользователи. Они не предполагали, что сами конечные пользователи будут просить ключи. Я писал им повторно по этому поводу недавно, но ответ был какой-то невнятный.

> Доброго дня.
> 
> В Home Assistant (рішення для розумного дому) додали інтеграцію з ukraine alarm: https://twitter.com/home_assistant/status/1523405897354993664. Чи є якийсь способ пришвидшити видачу API ключів? Чи може є можливість, щоб всі користувачі Home Assistant використовували єдиний ключ інтегрований в продукт?

> Доброго дня! На разі, АПІ не доступне для інтеграції з Home Assistant.

Я у них вчера переспросил что имеется в виду, жду ответа.

Я на неделе подниму свой сервер, который будет использовать мой ключ и создам новую библиотеку, которая будет использовать его.

**Comment by ntguest** [comment]
спасибо

**Comment by mvlasenko** [comment]
Дякую. Підняти проксі-АПІ буде вірним рішенням.

**Comment by PaulAnnekov** [comment]
Саппорт відповів:
> На разі доступний лише єдиний ключ для всіх користувачів.

Отже якщо ви кінцевий користувач, ваш вибір [uasiren](https://github.com/PaulAnnekov/uasiren) (вже інтегрована в HA https://github.com/home-assistant/core/pull/71754).
Цією бібліотекою слід користуватись для побудови свого рішення.
