### ISSUE TITLE
Сповіщення про "підвищену небезпеку" ніяк не відображено в інтеграції ukrainealarm для HomeAssistant.

### ISSUE THREAD

**Issue by ESlyusarenko** [PaulAnnekov/ukrainealarm#5]
Вітаю. 
Мобільний додаток Ukraine Alarm з недавнього часу почав сповіщати не тільки про тривогу за типом (Повітряна, хімічна, ядерна, та таке інше), а ще й додав стан для повітряної тривоги "підвищена небезпека". Це коли повітряні цілі наближаються саме до мого (обраного) району.
Сповіщення про "підвищену небезпеку" ніяк не відображено в інтеграції ukrainealarm для HomeAssistant.

Мені здається його потрібно додати як стан до Air. Там у вас зараз є 2 стани: 
- Безпечно
- Небезпечно

Будь ласка додайте туди ще й третій стан "Підвищена небезпека". 
Тобто для Типу тривоги Air (Повітряна) мало б бути три стани:
- Безпечно
- Небезпечно
- Підвищена небезпека.

Буду вам дуже вдячний якщо ви це реалізуєте. Цього стану дуже не вистачає.
Дякую.

**Comment by PaulAnnekov** [comment]
Нажаль я не можу знайти в API ukraine alarm цього індикатору https://api.ukrainealarm.com/swagger/index.html.

Можете хоча б скріншот показати як це в застосунку виглядає, а краще на мапі https://map.ukrainealarm.com/ ?

**Comment by ESlyusarenko** [comment]
Дякую за швидку відповідь.
Так, звісно. 
На цій мапі https://map.ukrainealarm.com/ такого сповіщення немає і не може бути.
Адже на https://map.ukrainealarm.com/ не можна обрати свій регіон чи район, щоб цей сайт додатково оповіщував саме про події в цьому регіоні. Сайт просто показує в якому регіоні тривога, але не показує де саме підвищена небезпека. А от у їх офіційному мобільному додатку це є.

Я для вас записав відео як це виглядає. Файл прикріпляю до цього коментаря. 
https://github.com/user-attachments/assets/81c5978d-3e6b-40ce-9f7f-dfb1a2a9b52b

Ось як вони пояснюють що таке ці сповіщення: 
![2024-10-04 00 41 41](https://github.com/user-attachments/assets/406dc25d-752f-4d4b-bb54-27c042f1b40b)

Також прикріпляю скриншот того як ці сповіщення виглядають у шторці телефона: 
![2024-10-04 00 38 36](https://github.com/user-attachments/assets/badd4fd1-6dc5-4881-aa34-d18ead647436)

Дякую.

**Comment by PaulAnnekov** [comment]
Нажаль я не бачу такої можливості в API. Спитав support цього API, можливо вони підкажуть.

**Comment by PaulAnnekov** [comment]
Відповіли:

> Доброго дня, ми не передаємо інформацію про підвищену небезпеку через АПІ.

**Comment by ESlyusarenko** [comment]
Добре, зрозумів. Шкода...
Але все одно дякую за вашу оперативність та намагання допомогти. 
Гарного Вам дня.
